import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class bookingpopup extends javax.swing.JFrame {

   
    public bookingpopup() {
        initComponents();
        addLabelListeners();
        addMouseListeners();
    }
    
    private void addMouseListeners() {
        // Add a mouse listener to the book1 label
        yess.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                // Change the text color or style when the mouse enters
                
            }

            @Override
            public void mouseExited(MouseEvent e) {
                // Reset the text color or style when the mouse exits
                // Reset to the default style
            }
        });
    }
    private void addLabelListeners() {
        yess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openForm();
            }
        });
        cancell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openHome();
            }
        });
    }
    
    private void openHome() {
    // Create an instance of Home and make it visible
    Tickets home = new Tickets();
    home.setDefaultCloseOperation(bookingpopup.DISPOSE_ON_CLOSE); // Dispose on close to avoid multiple instances
    home.setVisible(true);
    this.setVisible(false);
    }
    
    private void openForm() {
    // Create an instance of Home and make it visible
    BookingForm home = new BookingForm();
    home.setDefaultCloseOperation(bookingpopup.DISPOSE_ON_CLOSE); // Dispose on close to avoid multiple instances
    home.setVisible(true);
    this.setVisible(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cancell = new javax.swing.JLabel();
        yess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));

        jPanel1.setBackground(new java.awt.Color(26, 25, 25));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Are you sure you want to book the ticket?");

        cancell.setIcon(new javax.swing.ImageIcon("C:\\NetBeansProjects\\cancelbtn.png")); // NOI18N
        cancell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancellMouseExited(evt);
            }
        });

        yess.setIcon(new javax.swing.ImageIcon("C:\\NetBeansProjects\\yesbtn.png")); // NOI18N
        yess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yessMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                yessMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yess)
                        .addGap(34, 34, 34)
                        .addComponent(cancell, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancell, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yess, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancellMouseEntered
        cancell.setIcon(new javax.swing.ImageIcon("C:\\NetBeansProjects\\cancel2.png"));
    }//GEN-LAST:event_cancellMouseEntered

    private void cancellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancellMouseExited
        cancell.setIcon(new javax.swing.ImageIcon("C:\\NetBeansProjects\\cancelbtn.png"));
    }//GEN-LAST:event_cancellMouseExited

    private void yessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yessMouseEntered
        yess.setIcon(new javax.swing.ImageIcon("C:\\NetBeansProjects\\yes2.png"));
    }//GEN-LAST:event_yessMouseEntered

    private void yessMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yessMouseExited
        yess.setIcon(new javax.swing.ImageIcon("C:\\NetBeansProjects\\yesbtn.png"));
    }//GEN-LAST:event_yessMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookingpopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookingpopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookingpopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookingpopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookingpopup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel yess;
    // End of variables declaration//GEN-END:variables
}
